# dcmotor_chassis app 模块定义
# 主 Makefile 通过 include 读取此文件

APP_SOURCES = \
    app_robot/app_robot.c \
    app_cmd/app_cmd.c \
    app_chassis/app_chassis.c \
    app_motor/app_motor.c \
    app_error/app_error.c \
    app_sensor/app_sensor.c

APP_INCLUDES = \
    . \
    app_chassis \
    app_cmd \
    app_error \
    app_motor \
    app_robot \
    app_sensor
