#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成 lib_format 的十进制定宽查表。

输出: lib/lib_format/lib_format_dec3.inc
内容: 填充 static const char LIB_DEC3[1000][3] 的初始化行，"000" .. "999"

用途: LibFormat 的十进制整数转换低位(<1000)直接以数值为索引查表，
      高位用分层减法剥离，从而全程零除法（详见 lib_format.c）。
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "lib_format_dec3.inc"

with OUT.open("w") as f:
    f.write("/* Auto-generated by tools/gen_dec_tbl.py. DO NOT EDIT. */\n")
    for i in range(1000):
        d = "%03d" % i
        # 显式字符初始化：避免字符串字面量(含 NUL)赋给 char[3] 的截断警告
        f.write("    {'%s', '%s', '%s'},\n" % (d[0], d[1], d[2]))

print(f"wrote {OUT} ({1000} entries, {3 * 1000} B data)")
