# 在脚本模式下：隔离 include CubeMX 生成的 CMakeLists.txt，只导出变量
if(CMAKE_SCRIPT_MODE_FILE)
    if(NOT DEFINED CUBEMX_CMAKE_FILE)
        message(FATAL_ERROR "CUBEMX_CMAKE_FILE is not defined")
    endif()
    if(NOT DEFINED CUBEMX_HAL_DIR)
        message(FATAL_ERROR "CUBEMX_HAL_DIR is not defined")
    endif()
    if(NOT DEFINED CUBEMX_OUTPUT_FILE)
        message(FATAL_ERROR "CUBEMX_OUTPUT_FILE is not defined")
    endif()

    macro(add_library)
    endmacro()
    macro(target_sources)
    endmacro()
    macro(target_link_libraries)
    endmacro()
    macro(target_include_directories)
    endmacro()
    macro(target_link_directories)
    endmacro()
    macro(target_compile_definitions)
    endmacro()
    macro(target_compile_options)
    endmacro()
    macro(set_target_properties)
    endmacro()
    macro(enable_language)
    endmacro()

    set(CMAKE_CURRENT_SOURCE_DIR "${CUBEMX_HAL_DIR}/cmake/stm32cubemx")
    set(CMAKE_C_STANDARD 11)
    set(TOOLCHAIN_LINK_LIBRARIES "")

    include("${CUBEMX_CMAKE_FILE}")

    function(write_cmake_list output_file variable_name)
        file(APPEND "${output_file}" "set(${variable_name}\n")
        foreach(item IN LISTS ${variable_name})
            file(APPEND "${output_file}" "    [=[${item}]=]\n")
        endforeach()
        file(APPEND "${output_file}" ")\n\n")
    endfunction()

    file(WRITE "${CUBEMX_OUTPUT_FILE}" "# Generated by extract-cubemx-vars.cmake\n\n")
    write_cmake_list("${CUBEMX_OUTPUT_FILE}" MX_Defines_Syms)
    write_cmake_list("${CUBEMX_OUTPUT_FILE}" MX_Include_Dirs)
    write_cmake_list("${CUBEMX_OUTPUT_FILE}" MX_Application_Src)
    write_cmake_list("${CUBEMX_OUTPUT_FILE}" STM32_Drivers_Src)
    write_cmake_list("${CUBEMX_OUTPUT_FILE}" FreeRTOS_Src)
    write_cmake_list("${CUBEMX_OUTPUT_FILE}" MX_LINK_DIRS)
    write_cmake_list("${CUBEMX_OUTPUT_FILE}" MX_LINK_LIBS)
    return()
endif()

# 在项目模式下：提供给顶层 CMakeLists.txt 调用的函数
function(load_cubemx_vars cubemx_cmake_file hal_dir)
    set(output_file "${CMAKE_BINARY_DIR}/cubemx_vars_${HAL_CONFIG_NAME}.cmake")
    execute_process(
        COMMAND "${CMAKE_COMMAND}"
            -DCUBEMX_CMAKE_FILE=${cubemx_cmake_file}
            -DCUBEMX_HAL_DIR=${hal_dir}
            -DCUBEMX_OUTPUT_FILE=${output_file}
            -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
        RESULT_VARIABLE extract_result
        OUTPUT_VARIABLE extract_output
        ERROR_VARIABLE extract_error
    )

    if(NOT extract_result EQUAL 0)
        message(FATAL_ERROR "Failed to extract CubeMX variables:\n${extract_output}\n${extract_error}")
    endif()

    include("${output_file}")

    set(MX_Defines_Syms ${MX_Defines_Syms} PARENT_SCOPE)
    set(MX_Include_Dirs ${MX_Include_Dirs} PARENT_SCOPE)
    set(MX_Application_Src ${MX_Application_Src} PARENT_SCOPE)
    set(STM32_Drivers_Src ${STM32_Drivers_Src} PARENT_SCOPE)
    set(FreeRTOS_Src ${FreeRTOS_Src} PARENT_SCOPE)
    set(MX_LINK_DIRS ${MX_LINK_DIRS} PARENT_SCOPE)
    set(MX_LINK_LIBS ${MX_LINK_LIBS} PARENT_SCOPE)
endfunction()
